### ISSUE TITLE
Z-index bug of QICI update

### ISSUE THREAD

**Issue by trsh** [qiciengine/qiciengine#10]
I got yesterday an QICI editor update request when opening it. When I pressed OK, the design went to hell :). Playing around a bit with CSS, I realized that the update (and success) dialog was behind other elements because of smaller z-index. Editor was windows 7 64 bit Chrome (newest stable version).

**Comment by Morabaraba** [comment]
I to had the same issue os x 10.10.3, chrome 49.0.2623.87 (64-bit).

**Comment by huhudage** [comment]
We'll fixed this issue in the next version, thanks!

Currently, you can download the latest 1.0.9 version directly.

**Comment by linyiwei** [comment]
Fixed in 1.1.0 version https://github.com/qiciengine/qiciengine/blob/master/release-notes.md
