### ISSUE TITLE
Phaser.game.input.pointerOver() missing

### ISSUE THREAD

**Issue by justinboyd** [qiciengine/qiciengine#11]
It looks like the pointerOver() method has been removed from the Phaser library portion of the editor. The only other option is using the onEnter and onExit methods. I need to run an event that doesn't meet the onEnter and onExit criteria. I need to check if a pointer event happens outside of my node. Also, onEnter and onExit are only specific to users without a mouse and don't work with touch events.

Is this something that can be added in the next release?

**Comment by linyiwei** [comment]
In Phaser pointerOver is only valid for mouse enviroment, not for touch.
For touch you can listener to down and up event, and do the same thing like onEnter/onExit.

**Comment by justinboyd** [comment]
Since this is specific to mouse environment and not touch I would agree.
