### ISSUE TITLE
bug in demo "AsteroidsMovement"

### ISSUE THREAD

**Issue by Ogimle** [qiciengine/qiciengine#15]
bullets moves and ship orientation has different angle with code
`bullet.rotation = self.gameObject.rotation;`
![scrshot_087](https://cloud.githubusercontent.com/assets/181369/16612027/db706f30-4375-11e6-938e-2f42b6378f33.jpg)

**Comment by huhudage** [comment]
The rotation of bullet is right but the 'to' property of TweenPosition component is wrong.
Change the code
`tp.to = rigidbody.velocityFromRotation(bullet.rotation, 3000, tp.to);`
to
`tp.to = new qc.Point(tp.from.x + 3000 * Math.cos(bullet.rotation), tp.from.y + 3000 * Math.sin(bullet.rotation));`
will resolve this problem.

We'll fixed this problem in the next version, thank you for your feedback!

**Comment by Ogimle** [comment]
solution fixed bug, thanks
