### ISSUE TITLE
probably bug with script renaming

### ISSUE THREAD

**Issue by Ogimle** [qiciengine/qiciengine#17]
I rename script then try add it to node... File inspector has new name, component inspector has old name. Reload project, close/open page and load project dont helped.

![scrshot_106](https://cloud.githubusercontent.com/assets/181369/17317336/961adbf0-588d-11e6-81c0-5bb99395656a.jpg)

**Comment by huhudage** [comment]
How did you rename the script?

It seems you just rename the file name of the script, but not the class defined in the script.

In your condition, you need to edit the HUD.js, and replace 'HUD' to 'UI'.

**Comment by Ogimle** [comment]
> It seems you just rename the file name of the script, but not the class defined in the script.

i am sorry, you right, thanks
