### ISSUE TITLE
Actual source in Git?

### ISSUE THREAD

**Issue by ylluminate** [qiciengine/qiciengine#2]
I'm glad to see this released here, but we really should have the source fully available on here.  Would you like some help in getting this structured properly so that we can collaborate and use GitHub to its full potential?

**Comment by ylluminate** [comment]
So I wanted to help out here and worked on this to save you some effort.  Hopefully this helps:
https://github.com/orbitalimpact/qiciengine

I have taken all of your changes and committed them so that we can see the updates individually with the source.  I also took out the `node_modules` since that's something that can be installed by the developer.  I also inserted the readme files and the images in order to keep this as you had it described.

I also optimized your image sizes since they were a bit large.

I would recommend perhaps moving this repo to `qiciengine/qiciengine-releases` or just doing the releases right in the tree like `opal` does it: https://github.com/opal/opal/releases

Please let me know if you have any questions or could use any help!  We're really looking forward to using this with `opal-phaser`!

**Comment by linyiwei** [comment]
Thank @ylluminate for your great efforts! 

Currently the QICI Core is a single bundled JavaScript file (/lib/qc-core-debug.js) in QICI Editor, We are adding a lot of new features for QICI Engine heavily in our local git server, the source code has lots of Chinese comments, so make QICI Core project moving to github need some efforts to work, i am afraid that will slow down the development speed of our team. 

The first step goal of QICI Engine is helping users to make HTML5 games quickly, let more developers like to use the free unity-like QICI Editor tool and understand the behavioural oriented architecture of QICI Core. After QICI Engine become more stable and powerful, we will slow down the development speed to translating more Chinese comments to English and moving the whole QICI Core project from local git server to github repository. So putting QICI Core project in GitHub repository for community contributions is the second step goal for QICI Engine, at that time, we will provide more details on how to contribute effectively to the project.

Thank again @ylluminate, your efforts and suggestions motivate us a lot, we are looking forward to hearing more from community to make QICI Engine better!

**Comment by ylluminate** [comment]
Interesting, thanks for letting us know.  We're going to be giving this a solid look in the near term and how to really pull `opal-phaser` into this so as to allow ruby-on-the-web game development with QICI so that it's a first class citizen along side of JavaScript.
