### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by ylluminate** [qiciengine/qiciengine#3]
Hey I was thinking it might be a good idea to call this "Celadon" or "Celadon Engine" in English.  I've run this name "QICI" by a few people and have gotten really strange looks from them.  Some people even thought I was saying something "dirty" (off color; sexual).  No one really knows how to pronounce "QICI" in English since it is missing traditional demarquations.  

At any rate, I think just sticking to "Celedon Engine" would be much more appealing.  Hope this helps!

**Comment by jareguo** [comment]
+1

**Comment by Sean-LAI** [comment]
+1

**Comment by linyiwei** [comment]
Thank you for your advice. Internally we pronounce 'QICI' as 'kju:si'. 'QICI' is inspired by 'PIXI' (http://www.pixijs.com/), so the pronunciation can be borrowed from PIXI too. 

I made up this word by myself, the pronunciation is really a issue, but i like the word 'QICI', it is simple to be remembered, and has some connection with our company qcplay(http://www.qcplay.com/). 

'Celedon' is not easy for Chinese to remember and pronounce. Can you accept to call 'QICI' as 'kju:si' ?

**Comment by Sean-LAI** [comment]
Well，called "QICI“.

**Comment by wheatup** [comment]
I prefer the name 'QC', short, simple.
Like you said 'QICI' is inspired by 'PIXI', or maybe it's come from Chinese character 'Qing Ci', but they'll never know until you tell them. It's getting a little confusing, and brings a lot of pronunciation problems.
If it's sounds like 'kju:si' and looks like 'QICI', it might cause marketing problems, too.
This engine may build on it but it doesn't means we should ripoff it's name.

**Comment by linyiwei** [comment]
http://www.gamefromscratch.com/post/2016/01/14/A-Closer-Look-at-the-QICI-Engine.aspx

Before we have better idea, let's pronounce "QICI" character by character: Q,I,C,I. Just like Serapth did in the video: https://www.youtube.com/watch?v=cYo-eQSo55I
