### ISSUE TITLE
Dragging tilemap bin file not highlighting data input.

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine#4]
Hi,

Firstly, thanks for releasing this project!

I'm struggling to get tilemaps to work. I followed the instruction on http://docs.qiciengine.com/manual/Sample/Tilemap.html. 

After I added my *.txt and *.png, it creates the *.bin file. I then try to drag this to the Inspector, Tilemap, Data field. But the input box never turns yellow as in the video.

I'm using qici 1.0.6 and Chrome 47.0.2526.111 (64-bit) on os x. I tried it on my windows machine and encountered the same issue.

Attached is my files I'm testing with.

![tiles](https://cloud.githubusercontent.com/assets/11364489/12528800/adc25d9c-c1ab-11e5-9d77-cf15f7d94845.png)
[Untitled.txt](https://github.com/qiciengine/qiciengine/files/101730/Untitled.txt)

**Comment by linyiwei** [comment]
I have test it on qici 1.0.6, it works well on my Mac and Chrome
Do your name your png as "tiles.png" (Defined in txt file), and drag the txt and png in the same directory?
<img width="566" alt="screen shot 2016-01-23 at 3 37 17 pm" src="https://cloud.githubusercontent.com/assets/16269482/12529105/b20585e6-c1e7-11e5-9f3a-3ed7e97543d6.png">

**Comment by tianyagongcishi** [comment]
The value of tilesets's name property in your text file is 'tiles', so your image's name should be 'tiles.png'(the text file's name is unlimited). After dragging these two files to the project's folder, the editor will generate two .bin files: one for the image file, the other for the text file(and this is the asset file for Tilemap). Now drag the bin file which is named by your text file to the Inspector/Tilemap/Data field, it should be ok.

**Comment by Morabaraba** [comment]
Thanks all for the quick response.

I believe the problem was between the keyboard and chair, because after reading your suggestions I tried it again and it just works.

But I'm sure I followed the same process.

Anyway, thanks again!
