### ISSUE TITLE
API GameObject Sprite Link not working

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine#6]
From http://docs-cdn.qiciengine.com/api/gameobject/index.html if you click [sprite](http://docs-cdn.qiciengine.com/api/gameobject/Sprite.md) the site 404.

**Comment by linyiwei** [comment]
use _**.html not *_*.md

**Comment by Morabaraba** [comment]
Yes I figured as much but the next guy going through the documentation will click on the sprite link on the [GameObject Index Page](http://docs-cdn.qiciengine.com/api/gameobject/index.html), and not be sure why he is getting a 404.

I see it is only the sprite link that is broken.

**Comment by linyiwei** [comment]
You are right, i fixed it.
https://github.com/qiciengine/qiciengine-documentation/commit/16dfaec9d7c2531a290d63b243a4bb8076945fa6
