### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by Morabaraba** [qiciengine/qiciengine#8]
The play button stops the game. I'm in search of a restart button. 

Because at the moment I play my game.
Make changes to the code in the interactive mode, 
save the code and stop the game. 
To only after it loaded into edit mode do I press play. 
Which loads it into play mode again.

The loading times between play edit play takes time, and I wonder if a restart button will not make the round trip time a bit shorter?

**Comment by linyiwei** [comment]
You can select [Project/Reload Scene] from main menu to reload the game and keep in playing mode.
