### ISSUE TITLE
node.getScript can't find reference when game is published

### ISSUE THREAD

**Issue by justinboyd** [qiciengine/qiciengine#9]
I have a behavior script creating a prefab. When the prefab loads I'm getting the prefabs attached script using the getScript method [ex. myPrefab.getScript("scriptName")]. This works great in the editor. The problem happens when I publish the game. I get an error saying that it can't find the reference to "scriptName".

I have a temporary solution where I'm just using myNode.scripts[0].

**Comment by linyiwei** [comment]
You should use full className with package,  .getScript("a.b.c.YourClass') Not .getScript("YourClass')

**Comment by justinboyd** [comment]
Cool that works. Thank you!
